# Generated by Django 5.0.1 on 2024-03-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otome_game_website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="characters/"),
        ),
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="games/"),
        ),
    ]
