# Generated by Django 5.0.1 on 2024-03-02 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otome_game_website", "0002_character_image_game_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="otome_game_website.character",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="otome_game_website.character",
            ),
        ),
    ]
