# Generated by Django 5.0.1 on 2024-03-02 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otome_game_website", "0003_alter_comment_character_alter_rating_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
