# Generated by Django 5.0.1 on 2024-03-03 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otome_game_website", "0004_alter_rating_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="tag",
            new_name="tags",
        ),
    ]
